### ISSUE TITLE
Any support for 10X v4?

### ISSUE THREAD

**Issue by ECRWatson** [derijkp/scywalker#17]
Thanks for producing this tool. A colleague in the lab has had success deploying it for 10X v3.1-generated cDNA that was subsequently sequenced on a ONT device. I have sequenced ONT libraries made from 10X v4 cDNA (3'), and was wondering whether you had plans to support this? 

Many thanks,

ECRWatson

**Comment by wdecoster** [comment]
Hi,

Do you happen to know what was changed in v4 compared to v3?

Wouter

**Comment by ECRWatson** [comment]
Dear Wouter - Thanks for responding. I believe that the core difference is the barcoding: see 10X repository of whitelists [here](https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist). As per [this release](https://teichlab.github.io/scg_lib_structs/methods_html/10xChromium3.html) from the Teichmann lab, it doesn't seem that there is any other change to library structure.

**Comment by wdecoster** [comment]
Okay, I assume supporting that should be straightforward, but we will wait for @derijkp :)

**Comment by wdecoster** [comment]
Hi,

Just wanted to let you know that v4 will be supported!

Wouter

**Comment by derijkp** [comment]
Hi,

As Wouter said, support for v4 will be incorporated in the next version. 
You can actually already use v4 with the current version by downloading the barcode file (e.g. from https://teichlab.github.io/scg_lib_structs/data/10X-Genomics/3M-3pgex-may-2023.txt.gz) and using the option ```-sc_whitelist 3M-3pgex-may-2023.txt.gz```

Peter
