### ISSUE TITLE
Feature request: Allow for specification of output directory

### ISSUE THREAD

**Issue by nick-youngblut** [derijkp/scywalker#3]
As far as I can tell from the [README](https://github.com/derijkp/scywalker/blob/master/README.md), there is no option to specify the output directory for scywalker. 
Often users want/need to separate the input from the output (e.g., if the input is in a read-only directory).
Users could get around such a constraint by recreating the input directory structure via symlinks (as discussed in https://github.com/derijkp/scywalker/issues/1), but that is not so easy for the average user. If the symlink approach is needed (versus allowing for specification of the output directory), then it would be helpful to include a helper script for this task (e.g., the user provides a sample table similar to the input of nf-core/nanoseq, and the script produces the required set of symlinks in the required directory structure for input to scywalker).

**Comment by nick-youngblut** [comment]
@derijkp does https://github.com/derijkp/scywalker/commit/ee459c034e236eb7fcdbe627e219fb4308594095 allow for an output directory? I don't see that in the commit diff, or the updated README.

Also, is there a `--force` option to force a re-run from the start? Currently, it is a pain for re-run a failed pipeline run from the start, since the pipeline output files are intermixed with the input files, and one must manually delete the output files in order to "force" a re-run from the start.

**Comment by derijkp** [comment]
The given project directory is the output directory: If it does not exist, it will be created; project directories made using a samplesheet (by default) do not contain any input data (only softlinks to it). (btw, we have always used softlinks to have separation of source data and results, but with the  advantage that our users have easy access to the raw data through the links)

You can easily do a complete re-run from the start by deleting the complete projectdir first (as said, there should be no real data in it, just softlinks).

**Comment by nick-youngblut** [comment]
Thanks for the information! 

> we have always used softlinks to have separation of source data and results, but with the advantage that our users have easy access to the raw data through the links

I see the potential advantage, but given that most other bfx software uses dedicated input/output locations (e.g., wf-single-cell, sicelore, or FLAMES), scywalker is the exception, which can add complications to understanding the unique usage of scywalker versus other workflows.

> You can easily do a complete re-run from the start by deleting the complete projectdir firs

Then one must re-create the symlinks, correct? Which specific files much actually be deleted in order trigger a full re-run?
